name: CI Windows

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'paper/**'
      - 'tests/**'
      - 'mkdocs.yml'

jobs:
  build_windows_bazel:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v4

      - name: Install Bazelisk
        run: choco install bazelisk --no-progress

      - name: Ensure bazel points to bazelisk
        shell: pwsh
        run: |
          # on windows 'bazel' should already be on PATH via the choco package
          bazel version

      # test
      - name: Build the source
        run: bazel.exe build --config=windows //fastcpd/...

  test_windows_python:
    needs: build_windows_bazel
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Python version check
        run: python --version

      - name: Python library check
        run: python bazel/get_python_libs.py

      - name: Install dependencies
        run: make install

      - name: Build wheel
        run: make wheel
