name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libarmadillo-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "scikit-build-core>=0.10.0" "nanobind>=2.0" "packaging>=24.0" cmake
        pip install -e .
        pip install sphinx furo sphinx-copybutton

    - name: Build documentation
      run: |
        cd docs_sphinx
        make html

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_sphinx/_build/html
        cname: false  # Set to your custom domain if you have one
