name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black mypy

    - name: Run ruff
      run: ruff check fastcpd/
      continue-on-error: true

    - name: Run black (check only)
      run: black --check fastcpd/ tests/
      continue-on-error: true

    - name: Run mypy
      run: mypy fastcpd/
      continue-on-error: true
